-- Adjust names as needed
CREATE CATALOG IF NOT EXISTS retail;
USE CATALOG retail;
 
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold
